version: '2'
services:
  docker01_pg01:
    image: postgres:14.0
    volumes:
      - "./.postgres-data/data:/var/lib/postgresql/data"
    restart: "no"
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_USER: docker01_pg01
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: docker01_pg01
  docker01_mongo01:
    image: mongo:5.0
    volumes:
      - "./.mongo-data/db:/data/db"
    restart: "no"
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qwe
  docker01_mysql01:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: "no"
    ports:
      - 3307:3306
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: docker01_mysql01
      MYSQL_USER: docker01_mysql01
      MYSQL_PASSWORD: 123qwe
  docker01_nest01:
    build: ./nest01
    container_name: docker01_nest01
    restart: "no"
    working_dir: /app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./be:/app
      - docker01_v1:/app/node_modules
    command: "npm run start:dev"
    environment:
      ENV: DEV
  docker01_nuxt01:
    build: ./nuxt01
    container_name: docker01_next01
    restart: "no"
    working_dir: /app
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./fe:/app
      - docker01_v2:/app/node_modules
    command: "npm run dev"
  docker01_react01:
    build: ./react01
    container_name: react01
    restart: "no"
    working_dir: /app
    ports:
      - "3002:3002"
    expose:
      - "3002"
    volumes:
      - ./react01:/app
      - docker01_v3:/app/node_modules
    command: "npm run start"
  docker01_fastapi01:
    build: ./fastapi01
    container_name: fastapi01
    restart: "no"
    working_dir: /app
    ports:
      - "3003:3003"
    expose:
      - "3003"
    volumes:
      - ./fastapi01:/app
    command: "uvicorn main:app --host 0.0.0.0 --port 3003 --reload"
  docker01_react_redux_ts01:
    build: ./react_redux_ts01
    container_name: react_redux_ts01
    restart: "no"
    working_dir: /app
    ports:
      - "3004:3004"
    expose:
      - "3004"
    volumes:
      - ./react_redux_ts01:/app
      - docker01_v4:/app/node_modules
    command: "npm run start"
volumes:
  docker01_v1:
    external: true
  docker01_v2:
    external: true
  docker01_v3:
    external: true
  docker01_v4:
    external: true